In [2]:
!pip install scikit-learn


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
!pip uninstall numpy -y
!pip install numpy --upgrade --force-reinstall


Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 1.6 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/12.8 MB 1.7 MB/s eta 0:00:08
   ---- ----------------------------------- 1.3/12.8 MB 1.8 MB/s eta 0:00:07
   ---- ----------------------------------- 1.6/12.8 MB 1.8 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/12.8 MB 1.9 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.8 MB 2.0 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/12.8 MB 2.0 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.8 MB 2.1 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.8 MB 2.2 MB/s eta 0:00:04
   -------------- ------------------------- 4.7/12.8 MB 2.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
node2vec 0.5.0 requires numpy<2.0.0,>=1.24.0, but you have numpy 2.3.4 which is incompatible.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [4]:
corpus = [
    "Este es el primer documento.",
    "Este documento es el segundo documento.",
    "Y este es el tercer documento.",
    "¿Es este el primer documento?",
]

x = vectorizer.fit_transform(corpus)
print(x.shape)
print(x)

(4, 7)
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 20 stored elements and shape (4, 7)>
  Coords	Values
  (0, 3)	1
  (0, 2)	1
  (0, 1)	1
  (0, 4)	1
  (0, 0)	1
  (1, 3)	1
  (1, 2)	1
  (1, 1)	1
  (1, 0)	2
  (1, 5)	1
  (2, 3)	1
  (2, 2)	1
  (2, 1)	1
  (2, 0)	1
  (2, 6)	1
  (3, 3)	1
  (3, 2)	1
  (3, 1)	1
  (3, 4)	1
  (3, 0)	1


In [5]:
print(vectorizer.get_feature_names_out())

['documento' 'el' 'es' 'este' 'primer' 'segundo' 'tercer']


In [6]:
print(x.toarray())

[[1 1 1 1 1 0 0]
 [2 1 1 1 0 1 0]
 [1 1 1 1 0 0 1]
 [1 1 1 1 1 0 0]]


In [7]:
print(vectorizer.vocabulary_)

{'este': 3, 'es': 2, 'el': 1, 'primer': 4, 'documento': 0, 'segundo': 5, 'tercer': 6}


In [8]:
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2),min_df=1)

In [9]:
x_2 = bigram_vectorizer.fit_transform(corpus).toarray()
print(x_2.shape)
print(bigram_vectorizer.get_feature_names_out())
print(x_2)

(4, 19)
['documento' 'documento es' 'el' 'el primer' 'el segundo' 'el tercer' 'es'
 'es el' 'es este' 'este' 'este documento' 'este el' 'este es' 'primer'
 'primer documento' 'segundo' 'segundo documento' 'tercer'
 'tercer documento']
[[1 0 1 1 0 0 1 1 0 1 0 0 1 1 1 0 0 0 0]
 [2 1 1 0 1 0 1 1 0 1 1 0 0 0 0 1 1 0 0]
 [1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1]
 [1 0 1 1 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0]]


In [ ]:
# Trigaramas
bigram_vectorizer = CountVectorizer(ngram_range=(1, 3),min_df=1)
x_3 = bigram_vectorizer.fit_transform(corpus).toarray()
print(x_3.shape)
print(bigram_vectorizer.get_feature_names_out())
print(x_3)

(4, 30)
['documento' 'documento es' 'documento es el' 'el' 'el primer'
 'el primer documento' 'el segundo' 'el segundo documento' 'el tercer'
 'el tercer documento' 'es' 'es el' 'es el primer' 'es el segundo'
 'es el tercer' 'es este' 'es este el' 'este' 'este documento'
 'este documento es' 'este el' 'este el primer' 'este es' 'este es el'
 'primer' 'primer documento' 'segundo' 'segundo documento' 'tercer'
 'tercer documento']
[[1 0 0 1 1 1 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [2 1 1 1 0 0 1 1 0 0 1 1 0 1 0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1]
 [1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 1 1 0 0 0 0]]


In [ ]:
# Tetragramas
bigram_vectorizer = CountVectorizer(ngram_range=(1, 4),min_df=1)
x_4 = bigram_vectorizer.fit_transform(corpus).toarray()
print(x_4.shape)
print(bigram_vectorizer.get_feature_names_out())
print(x_4)

(4, 39)
['documento' 'documento es' 'documento es el' 'documento es el segundo'
 'el' 'el primer' 'el primer documento' 'el segundo'
 'el segundo documento' 'el tercer' 'el tercer documento' 'es' 'es el'
 'es el primer' 'es el primer documento' 'es el segundo'
 'es el segundo documento' 'es el tercer' 'es el tercer documento'
 'es este' 'es este el' 'es este el primer' 'este' 'este documento'
 'este documento es' 'este documento es el' 'este el' 'este el primer'
 'este el primer documento' 'este es' 'este es el' 'este es el primer'
 'este es el tercer' 'primer' 'primer documento' 'segundo'
 'segundo documento' 'tercer' 'tercer documento']
[[1 0 0 0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 1 0
  0 0 0]
 [2 1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1
  1 0 0]
 [1 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0
  0 1 1]
 [1 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 0
  0 0 0]]


In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer()
x_train_tfidf = tfidf_vect.fit_transform(corpus)
print(x_train_tfidf.shape)
print(tfidf_vect.get_feature_names_out())
print(x_train_tfidf.toarray())

(4, 7)
['documento' 'el' 'es' 'este' 'primer' 'segundo' 'tercer']
[[0.39896105 0.39896105 0.39896105 0.39896105 0.60276058 0.
  0.        ]
 [0.61221452 0.30610726 0.30610726 0.30610726 0.         0.5865905
  0.        ]
 [0.361028   0.361028   0.361028   0.361028   0.         0.
  0.69183461]
 [0.39896105 0.39896105 0.39896105 0.39896105 0.60276058 0.
  0.        ]]


In [15]:
# Trigaramas TF-IDF
tfidf_vect_3 = TfidfVectorizer(ngram_range=(1, 3))
x_train_tfidf_3 = tfidf_vect_3.fit_transform(corpus)
print(x_train_tfidf_3.shape)
print(tfidf_vect_3.get_feature_names_out())
print(x_train_tfidf_3.toarray())

(4, 30)
['documento' 'documento es' 'documento es el' 'el' 'el primer'
 'el primer documento' 'el segundo' 'el segundo documento' 'el tercer'
 'el tercer documento' 'es' 'es el' 'es el primer' 'es el segundo'
 'es el tercer' 'es este' 'es este el' 'este' 'este documento'
 'este documento es' 'este el' 'este el primer' 'este es' 'este es el'
 'primer' 'primer documento' 'segundo' 'segundo documento' 'tercer'
 'tercer documento']
[[0.20913449 0.         0.         0.20913449 0.31596574 0.31596574
  0.         0.         0.         0.         0.20913449 0.2558015
  0.40076248 0.         0.         0.         0.         0.20913449
  0.         0.         0.         0.         0.31596574 0.31596574
  0.31596574 0.31596574 0.         0.         0.         0.        ]
 [0.31028974 0.29730268 0.29730268 0.15514487 0.         0.
  0.29730268 0.29730268 0.         0.         0.15514487 0.18976445
  0.         0.29730268 0.         0.         0.         0.15514487
  0.29730268 0.29730268 0.      

In [16]:
# Tetragaramas TF-IDF
tfidf_vect_3 = TfidfVectorizer(ngram_range=(1, 4))
x_train_tfidf_3 = tfidf_vect_3.fit_transform(corpus)
print(x_train_tfidf_3.shape)
print(tfidf_vect_3.get_feature_names_out())
print(x_train_tfidf_3.toarray())

(4, 39)
['documento' 'documento es' 'documento es el' 'documento es el segundo'
 'el' 'el primer' 'el primer documento' 'el segundo'
 'el segundo documento' 'el tercer' 'el tercer documento' 'es' 'es el'
 'es el primer' 'es el primer documento' 'es el segundo'
 'es el segundo documento' 'es el tercer' 'es el tercer documento'
 'es este' 'es este el' 'es este el primer' 'este' 'este documento'
 'este documento es' 'este documento es el' 'este el' 'este el primer'
 'este el primer documento' 'este es' 'este es el' 'este es el primer'
 'este es el tercer' 'primer' 'primer documento' 'segundo'
 'segundo documento' 'tercer' 'tercer documento']
[[0.18194407 0.         0.         0.         0.18194407 0.27488576
  0.27488576 0.         0.         0.         0.         0.18194407
  0.22254371 0.34865773 0.34865773 0.         0.         0.
  0.         0.         0.         0.         0.18194407 0.
  0.         0.         0.         0.         0.         0.27488576
  0.27488576 0.34865773 0.   